name: Build image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMG_NAME: ${{ github.repository }}

jobs:
  run_build:
    permissions:
      contents: read
      packages: write
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get version
        id: vars
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker"
          push: true
          tags:  ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.vars.outputs.tag }}
